$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: myEnvi
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20231003.v1
conda_file:
  name: sklearn-env
  dependencies:
    - python=3.8
    - scikit-learn
    - pandas
    - numpy
    - pip
