$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: >
  python train.py --data_path ${{inputs.train_data}} --model_path ${{outputs.trained_model}}
inputs:
  train_data:
    type: uri_file
    path: azureml:final_dataset@latest
    mode: download
outputs:
  trained_model:
    type: uri_file
environment: azureml:AzureML-Scikit-learn0.24-Cuda11-OpenMpi4.1.0-py36@latest
compute: azureml:cpu-cluster
description: "Training job for activity recognition"
experiment_name: "activity-recognition-experiment"
